option domain-name "zakharov.g4133.guap.local";
option domain-name-servers 10.33.13.1;
default-lease-time 2592600;
max-lease-time 2599200;
ddns-update-style interim;
update-static-leases on;
allow client-updates;
key DHCP_UPDATER {
    algorithm HMAC-SHA256;
    secret "eTPgbLjR8JmUm3XyNQgTDAgQ4f7i0PpHKmNdiNa42Qk=";
}
zone zakharov.g4133.guap.local. {
    primary 10.33.13.1;
    key DHCP_UPDATER;
}
zone 13.33.10.in-addr.arpa. {
    primary 10.33.13.1;
    key DHCP_UPDATER;
}
zone 13.168.192.in-addr.arpa. {
    primary 10.33.13.1;
    key DHCP_UPDATER;
}
subnet 10.33.13.0 netmask 255.255.255.0 {
    option routers 10.33.13.2;
    range 10.33.13.100 10.33.13.200;
}
subnet 192.168.13.0 netmask 255.255.255.0 {
    option routers 192.168.13.1;
    range 192.168.13.100 192.168.13.200;
}
