[global] 
   workgroup = WORKGROUP 
   log file = /var/log/samba/log.%m 
   max log size = 1000 
   logging = file 
   panic action = /usr/share/samba/panic-action %d 
   server role = standalone server 
   obey pam restrictions = yes 
   unix password sync = yes 
   passwd program = /usr/bin/passwd %u 
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *passw$ 
   pam password change = yes 
   map to guest = bad user 
   usershare allow guests = no 

[homes] 
   comment = Home Directories 
   browseable = no 
   read only = yes 
   create mask = 0700 
   directory mask = 0700 
   valid users = %S 

[samba_common] 
   path = /srv/samba/common 
   writable = yes 
   browseable = yes 
   valid users = @writers, @readers 
   create mask = 0775 
   directory mask = 0775 

[samba_private] 
   path = /srv/shared/private
   writable = yes 
   browseable = yes 
   valid users = @writers, @readers 
   create mask = 0775 
   directory mask = 0775 
   hosts deny = 192.168.13.100/24
